version: '3.4'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@hiper.com.br"
      PGADMIN_DEFAULT_PASSWORD: Hiper123
    volumes:
      - ./pgadmin-data:/var/lib/postgresql/data
    ports:
      - 8002:80
    restart: always